### ISSUE TITLE
Slide numbers fail to be preserved

### ISSUE THREAD

**Issue by ozsu** [maxonthegit/PPspliT#22] opened 2024-03-20 15:39 UTC
I am having a problem with PPspliT (currently running 2.6). It does split the animated sides correctly, but assigns consecutive page numbers to each animation slide rather than maintaining the same slide number. I have been using PPslIT for some time and it worked properly. This problem exists in the older version 1.24, and after I upgraded to 2.6 and happens on both MacOS (Ventura) and on Windows versions of Powerpoint. I am not sure if a recent update of Powerpoint broke things or whatever, but it is an issue.

By the way, I have tried both Preserve slide numbers and Preserve slide numbers and add a subindex and it is the same problem.

==Tamer

**Comment by maxonthegit** [comment] 2024-03-21 22:08
Thank you very much @ozsu for reporting this issue.
I have made a few tests with the regression test suite as well as with other complex presentations from former academic contributions, both in Windows and in macOS. Oddly enough, despite the presence of many elaborate animations, slide numbering has always been preserved as expected. My PowerPoint release is the latest available in the Microsoft 365 subscription as of today.

Could you please submit a minimal sample of slide deck where you have observed preservation of slide numbers to predictably fail?

As a side note consider that, in the (unlikely) case in which PPspliT raises an error while splitting, all its settings in the ribbon are lost (i.e., _Split on click-triggered animations_ and _Preserve slide numbers_) and need to be reset before attempting to split again (i.e., by disabling and re-enabling _Split on click-triggered animations_ or by turning _Preserve slide numbers_ to a different setting and then switching it back to the desired one). I am not sure this is your case anyway.

**Comment by ozsu** [comment] 2024-03-22 00:07
Thank you Massimo. I have done the resetting -- changed the setting to something else and then changing it back -- but that did not fix things for me. 

Perhaps the size of the presentation makes a difference? This one has 120+ slides. My earlier ones where everything worked were smaller. I'll try a smaller one to see. I will also send you my slide deck backchannel. Perhaps there is something in my system setup that got screwed.

**Comment by maxonthegit** [comment] 2024-03-28 22:05
Thank you @ozsu.
I have received your sample slide deck. Despite being impressive, its size should not be an issue for PPspliT, and this is confirmed by the fact that the add-in fulfils its task without fatal errors.
In your specific case, failure to preserve slide numbers is due to a [slide master](https://support.microsoft.com/en-us/office/what-is-a-slide-master-b9abb2a0-7aef-4257-a14e-4329c904da54) structure that impacts [known limitation 13](https://github.com/maxonthegit/PPspliT/blob/b3d5e48ebbc297522c83a82dbd1c5d4fd391c7be/README.md#known-limitations). Further details, as well as a workaround, follow.

# Issue breakdown
## Background
Slide numbers appearing in slide footers are actually text boxes containing a special dynamically updated field that can be inserted in any text paragraph using a specific button:
![image](https://github.com/maxonthegit/PPspliT/assets/771877/74578fbe-9ba4-426f-817e-c3174e773d24)
Adjusting slide numbers so that each slide resulting from splitting has the same number of the original slide it derives from requires replacing every occurrence of this special field with a statically assigned value. Due to the lack of PowerPoint VBA primitives to detect the presence of this field in a generic text paragraph, at its best PPspliT can only "[bake](https://github.com/maxonthegit/PPspliT/blob/b3d5e48ebbc297522c83a82dbd1c5d4fd391c7be/src/PPT12%2B/PPspliT.bas#L1341)" the contents of text boxes that are most likely to contain this field, namely all the 3 footer placeholders found in the slide master:
![image](https://github.com/maxonthegit/PPspliT/assets/771877/c5519977-1efb-4521-8f1a-594b826d52ea)
In other words, PPspliT can only adjust slide numbers that appear in such special text boxes in the slide master (also see [this code fragment](https://github.com/maxonthegit/PPspliT/blob/b3d5e48ebbc297522c83a82dbd1c5d4fd391c7be/src/PPT12%2B/PPspliT.bas#L1356)).

## Evidence of the issue
Your slide deck breaks the above assumption because slide numbers are not framed in any of the aforementioned special text boxes. As further evidences and consequences:
* attempting to use the _Insert_/_Header and Footer_ function to set the visibility of slide numbers always fails, as they keep being marked as _not_ visible:
    <img src="https://github.com/maxonthegit/PPspliT/assets/771877/d6be34c8-4408-4d17-b2fc-6c4d3004bf34" height=230>
    <img src="https://github.com/maxonthegit/PPspliT/assets/771877/a0b12537-3312-424e-a7be-3b3f2cdd8246" height=600>
* after switching to the [slide master view](https://support.microsoft.com/en-us/office/what-is-a-slide-master-b9abb2a0-7aef-4257-a14e-4329c904da54), selecting the first template in the left-side list (i.e., the slide master itself) and clicking on the master layout button, slide numbers are unchecked (i.e., _not_ displayed):
    <img src="https://github.com/maxonthegit/PPspliT/assets/771877/162c12e4-9efe-4293-aa8b-b77fb5fa7749" height=250>

# Workaround
While the purpose of displaying slide numbers is still accomplished in your deck, working around this issue requires a slight adjustment to your slide master to make it more compliant with the standard expected structure. Here are the required steps:
1. Switch to the [slide master view](https://support.microsoft.com/en-us/office/what-is-a-slide-master-b9abb2a0-7aef-4257-a14e-4329c904da54).
2. Select the first template in the left-side list (i.e., the slide master).
3. Select the text box containing the slide number in the lower right and delete it.
    ![image](https://github.com/maxonthegit/PPspliT/assets/771877/62c1a483-b39e-4099-81c0-192465242471)

5. Click on the _Master Layout_ button and enable _Slide number_. A new text box will be created in the lower right, and this time it will be recognized as a standard slide number placeholder.
6. For each slide layout in the left-side list:
    * select the layout
    * if the current layout does _not_ contain a slide number, then just skip to the next slide layout
    * otherwise, select the text box containing the slide number in the lower right and delete it
    * click on the _Footer_ checkbox (it should be already checked and will remain checked): this will create a new text box  containing the slide number which, being inherited from the slide master, will be treated as a standard slide number placeholder
       <img src="https://github.com/maxonthegit/PPspliT/assets/771877/0e3a9753-f130-423c-a86d-81fde70ed6ea" height=200>
7. Close the slide master view and switch back to the normal view.
8. Click on _Insert_/_Header and Footer_ and enable numbers for all slides.
        <img src="https://github.com/maxonthegit/PPspliT/assets/771877/d6be34c8-4408-4d17-b2fc-6c4d3004bf34" height=230>

Despite the above screenshots being from PowerPoint for macOS, the same procedure applies to PowerPoint for Windows as well.

----

Your slide deck should now split successfully with slide numbers preserved as expected.

**Comment by maxonthegit** [comment] 2024-04-11 20:41
As mentioned in the previous comment and documented in [known limitation 13](https://github.com/maxonthegit/PPspliT/blob/b3d5e48ebbc297522c83a82dbd1c5d4fd391c7be/README.md#known-limitations), adjustment of slide numbers can only be carried out when these are put in standard slide number footers.
Since the slide master of presentations that break this assumption can be edited to comply with it, I am closing the issue.

**Closed by maxonthegit** 2024-04-11 20:41 UTC
