### ISSUE TITLE
PPspliT 1.27 clipboard-related error (number -2147221040 - Method 'Copy' failed)

### ISSUE THREAD

**Issue by CollinCodez** [maxonthegit/PPspliT#12] opened 2022-07-04 16:42 UTC
![image](https://user-images.githubusercontent.com/79947287/177192305-d5400e62-890c-4a0d-adf2-a2db81ea0cd2.png)
When working on splitting up a slideshow, I encountered this error pictured above. This ends up meaning [CLIPBRD_E_FIRST](https://www.magnumdb.com/search?q=-2147221040). 
Here is a screenshot of the slide that it occurs on and the animations on it 
![image](https://user-images.githubusercontent.com/79947287/177193697-3f51681b-c480-4a25-9bae-ebec3e82b298.png)
The timing is set to 0 seconds on the first group.
I have also had this happen on a few other slides in this presentation that had similar starts to the animations in the slide.

**Comment by maxonthegit** [comment] 2022-07-04 17:51
Hi @CollinCodez,

I am sorry to read that you are experiencing this issue.
I am not aware of any problems in dealing with a foremost animation step starting 0 seconds after the beginning of the timeline, and a quick test did not reveal any issues either.

Please review the advice about the system clipboard on page 3 of the [usage instructions](http://www.maxonthenet.altervista.org/downloads/PPspliT/PPspliT-howto.pdf) as well as the suggestions in [this comment](https://github.com/maxonthegit/PPspliT/issues/7#issuecomment-780845903) of #7 and check whether these help address your issue(s).

Otherwise, it would be useful if you could share a minimal sample of presentation that is enough to trigger the problem. You can send it to [my e-mail address](http://www.maxonthenet.altervista.org/contacts.php) in case you want to keep it private.

**Comment by CollinCodez** [comment] 2022-07-05 17:12
[PPspliT breaker slide example.pptx](https://github.com/maxonthegit/PPspliT/files/9048229/PPspliT.breaker.slide.example.pptx)
I took that slide that breaks it and put it into its own slideshow, so here is that. If you would like the whole thing with more examples let me know and I can send that over to you as well

**Comment by maxonthegit** [comment] 2022-07-05 19:18
Thank you @CollinCodez.
Interestingly, your sample presentation splits flawlessly in my PowerPoint instance, as displayed in the following screencam:
![PPspliT breaker_split](https://user-images.githubusercontent.com/771877/177398526-d76369d8-de5d-4a7a-bf59-897550f2ff7a.gif)

Two additional observations:
1. The animation timeline in your "breaker" sample slightly differs from the one in [your original screenshot](https://user-images.githubusercontent.com/79947287/177193697-3f51681b-c480-4a25-9bae-ebec3e82b298.png): the last step in the latter is triggered by a mouse click, whereas in the former all the animation steps are supposed to happen at once when the slide is displayed (as a result, no animations are visible for the audience). Even changing the last animation to become mouse-triggered as in your screenshot has no adverse effects on the operation of PPspliT.
2. Fonts (i.e., character appearance) in your screenshot differ from those in the presentation you have shared.

None of these observations should be really relevant to troubleshoot this issue, but they are worth mentioning.

Are you sure that the very same file that you have shared is enough to cause PPspliT to fail? In this case, did you review the suggestions that I have proposed in my previous comment concerning possible interferences with the system clipboard while the splitting takes place?

**Comment by CollinCodez** [comment] 2022-07-13 16:08
I've got a bit of an update: I did have around 4 Remote Desktop softwares running in the background at the time, and I think I was connected on Teamviewer at the time. Last night I believe I replicated the issue with the softwares running in the background but none connected, though after closing all of them completely I got it to work. I'll look into it more tonight and figure out exactly which one(s) were interfering.

I do believe I also noticed some other behavior with the splitting that was not ideal like leaving behind bullet points, but that is unrelated to the other issue I was having.

**Comment by CollinCodez** [comment] 2022-07-19 00:34
So I figured out what the issue was: Parsec running in the system tray (noone connected) seems to have been the cause of the issue. Once parsec is fully closed, this tool works GREAT! I have tested it on a few different slideshows and it seems to do them perfectly!
Parsec only copies text and not images/files, so this is really kinda interesting.

I am so glad to have this thing working, this tool is great!

If you have any questions about Parsec, let me know and I may know myself, or can probably get a response from one of the devs about it.

**Comment by maxonthegit** [comment] 2022-07-21 21:15
Thank you very much for your update and for your appreciation!
I am glad that you have finally figured out what the issue was. Indeed, remote desktop clients may interfere with the system clipboard in order to share it with the remote system (having 4 simultaneously running instances is definitely not a common condition either!).

The list of tools that may disturb PPspliT operation is therefore updated as follows:
* Shared clipboard functions of virtualization environments. For example, in #3 is discussed [how to disable clipboard sharing](https://www.virtualbox.org/manual/ch03.html#settings-general-advanced) in [VirtualBox](https://www.virtualbox.org/).
* The clipboard history function of Windows 10. [Here](https://www.howtogeek.com/671222/how-to-enable-and-use-clipboard-history-on-windows-10/) is explained how to disable it.
* Remote desktop tools such as TeamViewer, Anydesk, Parsec, Splashtop and other similar tools, especially while a session is open.

I am further looking into this problem and will keep this issue open for a while just in case I find a viable solution to allow coexistence with such tools.

**Comment by maxonthegit** [comment] 2022-07-21 21:16
Related to #3, #7.

**Comment by CollinCodez** [comment] 2022-07-29 15:36
I have been using this tool a good amount over the past few weeks, and with other confilicting software closed I have occassionally ended up getting this same error when converting a long slideshow (50+ slides) all at once. If I do the chunks individually, it is fine, but if I try to do everything at once I end up getting this error. I can email you a few examples of slideshows I have encountered this on if you would like

**Comment by maxonthegit** [comment] 2022-08-03 20:33
Yes, you can send a sample (via e-mail), thank you.
However, as I have written in advance, even the slide deck used to troubleshoot this issue ([PPspliT breaker slide example.pptx](https://github.com/maxonthegit/PPspliT/files/9048229/PPspliT.breaker.slide.example.pptx)) is enough to sometimes trigger the unexpected behavior you are mentioning.
I am further investigating this problem but, especially considering the upcoming vacations, it will likely take me several weeks to try to come to a verdict.

**Comment by felkel** [comment] 2022-10-24 21:09
Hello, 
I have probably found the problem on Windows11.
System/Clipboard / Clipboard history
- enabled => PPsplit crashes
- disabled => PPsplit works without any problem

Thank you for the excellent plugin.
Petr 

PS: I do not have English Windows, so the tab names may be different

**Comment by maxonthegit** [comment] 2022-11-08 22:30
Thank you @felkel for reporting this observation. Indeed, this seems to confirm a similar behavior experienced in Windows 10, as documented in [this comment](https://github.com/maxonthegit/PPspliT/issues/7#issuecomment-780845903) of #7.

Although the actual cause of this class of interferences is not yet fully understood, a likely explanation is that processing by third-party applications can alter clipboard contents and/or timing of clipboard accesses in a way that triggers race conditions in the execution of PPspliT. So far, the best known workaround is to prevent such interferences from happening altogether, but this issue highlights that in a few corner cases race conditions may still occur without being caused by any specific applications. Investigation on this specific case is still ongoing (sorry, I am not able to provide an ETA).

**Comment by maxonthegit** [comment] 2022-12-19 15:27
This issue, as well as #3 and #7, should be definitively addressed by [PPspliT release 2.0](https://github.com/maxonthegit/PPspliT/releases/tag/v2.0), freshly published.

**Closed by maxonthegit** 2022-12-19 15:27 UTC
