### ISSUE TITLE
Failed to detect any Office releases

### ISSUE THREAD

**Issue by lars-vc** [maxonthegit/PPspliT#10] opened 2021-06-06 13:02 UTC
Upon installing I receive this popup,
![image](https://user-images.githubusercontent.com/57136208/120925200-d04e6900-c6d7-11eb-813f-0cfb8e1f2342.png)
And after opening up powerpoint again, the extension isn't installed (as mentioned in the popup). I have an official windows/ office installation so I don't know what I am doing wrong?

**Comment by lars-vc** [comment] 2021-06-06 13:09
I have managed to manually add the extension, (first run gave some fatal errors, but second run did the job ¯\_(ツ)_/¯)

**Comment by etiennebeaulac** [comment] 2021-09-22 19:59
Hi! I am encountering the same issue. Could you please indicate how you manually added the extension to PowerPoint?
Thank you very much!

**Comment by etiennebeaulac** [comment] 2021-09-23 00:40
I figured it out, here's how for anyone who might stumble on this issue later :
1. Download the latest `PPspliT-setup.exe` from [Releases](https://github.com/maxonthegit/PPspliT/releases/).
2. Using an archive manager, extract the content from the installer (as if it were a zip file).
3. In PowerPoint, click on the File tab, then on Options.
4. In the Options dialog, click on Add-ins.
5. In the Manage dropdown at the bottom, select PowerPoint Add-ins, then click on Go.
6. Click on Add New, then select `PPspliT.ppam` from the folder you extracted at step 2.

**Comment by maxonthegit** [comment] 2021-09-25 20:09
Hi @etiennebeaulac,

I am sorry to read that you are experiencing this issue, yet happy to see that you have already found a fix by yourself.
Manual installation was only mentioned briefly in [this old comment](https://github.com/maxonthegit/PPspliT/issues/1#issuecomment-668811578), but your step-by-step guide may be handy for any future occurrences of the same problem (hopefully few).
It would still be useful if you could report the full release number of the Office release you are trying to use, in order to better understand the reason for the installer failing to detect it.

Thank you.

**Comment by etiennebeaulac** [comment] 2021-09-27 23:39
Hi @maxonthegit ,

I am using "Microsoft PowerPoint for Office 365 MSO (16.0.12430.20112) 32 bits".

Hope it is the information you need. If it is not, let me know!

**Comment by maxonthegit** [comment] 2021-09-28 17:59
Hi @etiennebeaulac,

yes: that is exactly the piece of information I was looking for, thank you. This is a bit strange, as I could successfully execute the [latest installer](https://github.com/maxonthegit/PPspliT/releases/download/v1.24/PPspliT-setup.exe) without any errors on a system with the following PowerPoint release installed:
`Microsoft® PowerPoint® per Microsoft 365 MSO (16.0.14326.20384) a 32 bit`

@lars-vc's comment suggests that a second run of the installer may succeed but, even if it did (which I doubt for your case), it would still be unclear why the first one should have failed: maybe a registry permission issue?
Without any further evidence and a fairly easy workaround in place there is not much that I can do. However, I can still suggest to have a look at #1, where a similar PowerPoint detection problem was reported for the case of an OEM installation (i.e., performed by the PC manufacturer).

Thank you for any additional investigation steps you are available to perform.

**Comment by lars-vc** [comment] 2021-09-29 05:40
Hi, je upon my first run I got some weird fatal error (its been too long to remember the exact error message), but after I ran it again it gave some other stuff but the animations were split. So I didnt really look further into it. I could attempt to replicate it with the same ppt later, if you'd like that.

**Comment by etiennebeaulac** [comment] 2021-09-30 05:04
@maxonthegit,

I redownloaded the latest installer and tried to install it again, thrice. Still "failed to automatically detect any Office releases".

I ran all the `reg query ...` commands mentionned in #1 and I seem to be in **exactly** the same situation as pburgio.

You mentionned there that this is a *won't fix* situation, which I completely understand. I truly thank you for taking the time to investigate this issue with me! Might I only suggest to add instructions in the README (or anywhere else) on how to perform a manual installation? Your plugin is so useful and easy to use, it would be a shame if someone was discouraged from using it because of this particular issue.

**Comment by maxonthegit** [comment] 2021-10-01 20:31
Thank you @lars-vc for double checking. By reading about your experience, it seems that you might have encountered some difficulties during the split process itself, whereas this issue specifically addresses failures at the time of _installing_ the add-in.

Thank you @etiennebeaulac for confirming the issue to resemble the one discussed in #1. Following your suggestion, I have added a _Troubleshooting_ section to the [usage instructions](http://www.maxonthenet.altervista.org/downloads/PPspliT/PPspliT-howto.pdf) where manual installation steps are also discussed.

Thank you again for all your feedback!

**Comment by maxonthegit** [comment] 2021-10-01 20:31
Duplicate of #1.

**Closed by maxonthegit** 2021-10-01 20:31 UTC
